packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Runtime dependencies
  zod: ^4.3.6
  dotenv: ^17.2.4
  fastify: ^5.7.4
  '@fastify/sensible': ^6.0.4
  '@fastify/cors': ^11.2.0
  fastify-type-provider-zod: ^6.1.0
  fastify-plugin: ^5.1.0

  # Dev dependencies
  typescript: ^5.7.3
  '@types/node': ^22.10.2
  eslint: ^9.18.0
  tsx: ^4.21.0
  pino-pretty: ^13.1.3
