packages:
  - apps/*
  - packages/*

catalog:
  '@fastify/cors': ^11.2.0
  '@fastify/sensible': ^6.0.4
  '@types/node': ^22.10.2
  dotenv: ^17.2.4
  eslint: ^9.18.0
  fastify: ^5.7.4
  fastify-plugin: ^5.1.0
  fastify-type-provider-zod: ^6.1.0
  pino-pretty: ^13.1.3
  tsx: ^4.21.0
  typescript: ^5.7.3
  zod: ^4.3.6
