// Sample Decksmith data — fictional but realistic MTG decks & cards.
// Used across the UI-kit screens. No real Scryfall art; color identity drives
// the placeholder gradients in DeckCard / CardThumb.
window.DS_DATA = {
  user: { name: 'Jeremie Drazic', handle: 'jeremie' },

  decks: [
    {
      id: 'urdragon',
      name: 'The Ur-Dragon',
      commander: 'The Ur-Dragon',
      format: 'Commander',
      colors: 'wubrg',
      count: 100,
      coverage: 87,
      price: '142 €',
      updated: '2d ago',
    },
    {
      id: 'yawgmoth',
      name: 'Yawgmoth Reanimator',
      commander: 'Yawgmoth, Thran Physician',
      format: 'Commander',
      colors: 'bg',
      count: 100,
      coverage: 72,
      price: '89 €',
      updated: '5d ago',
    },
    {
      id: 'kinnan',
      name: 'Kinnan Ramp',
      commander: 'Kinnan, Bonder Prodigy',
      format: 'Commander',
      colors: 'gu',
      count: 98,
      coverage: 95,
      price: '210 €',
      updated: '1w ago',
    },
    {
      id: 'krenko',
      name: 'Krenko Goblins',
      commander: 'Krenko, Mob Boss',
      format: 'Commander',
      colors: 'r',
      count: 100,
      coverage: 64,
      price: '78 €',
      updated: '2w ago',
    },
    {
      id: 'atraxa',
      name: 'Atraxa Superfriends',
      commander: 'Atraxa, Praetors\u2019 Voice',
      format: 'Commander',
      colors: 'wubg',
      count: 100,
      coverage: 81,
      price: '305 €',
      updated: '3w ago',
    },
    {
      id: 'mono-w',
      name: 'Heliod Lifegain',
      commander: 'Heliod, Sun-Crowned',
      format: 'Modern',
      colors: 'w',
      count: 60,
      coverage: 91,
      price: '124 €',
      updated: '1mo ago',
    },
  ],

  // Cards for collection / search grids
  cards: [
    {
      name: 'Sol Ring',
      set: 'C21',
      cost: '{1}',
      colors: 'c',
      rarity: 'uncommon',
      qty: 4,
      price: '1.80',
      condition: 'NM',
    },
    {
      name: 'Cyclonic Rift',
      set: 'RTR',
      cost: '{6}{U}',
      colors: 'u',
      rarity: 'rare',
      qty: 1,
      price: '28.50',
      condition: 'LP',
    },
    {
      name: 'Sheoldred, the Apocalypse',
      set: 'DMU',
      cost: '{2}{B}{B}',
      colors: 'b',
      rarity: 'mythic',
      qty: 1,
      price: '64.00',
      condition: 'NM',
    },
    {
      name: 'Llanowar Elves',
      set: 'M19',
      cost: '{G}',
      colors: 'g',
      rarity: 'common',
      qty: 8,
      price: '0.25',
      condition: 'NM',
    },
    {
      name: 'Lightning Bolt',
      set: 'MH2',
      cost: '{R}',
      colors: 'r',
      rarity: 'common',
      qty: 4,
      price: '1.20',
      condition: 'NM',
    },
    {
      name: 'Swords to Plowshares',
      set: 'STA',
      cost: '{W}',
      colors: 'w',
      rarity: 'uncommon',
      qty: 3,
      price: '2.40',
      condition: 'NM',
    },
    {
      name: 'Atraxa, Praetors\u2019 Voice',
      set: 'C16',
      cost: '{G}{W}{U}{B}',
      colors: 'wubg',
      rarity: 'mythic',
      qty: 1,
      price: '34.00',
      condition: 'NM',
    },
    {
      name: 'Birds of Paradise',
      set: 'M12',
      cost: '{G}',
      colors: 'g',
      rarity: 'rare',
      qty: 2,
      price: '8.90',
      condition: 'LP',
    },
    {
      name: 'Counterspell',
      set: 'MH2',
      cost: '{U}{U}',
      colors: 'u',
      rarity: 'common',
      qty: 4,
      price: '0.90',
      condition: 'NM',
    },
    {
      name: 'Demonic Tutor',
      set: '2XM',
      cost: '{1}{B}',
      colors: 'b',
      rarity: 'rare',
      qty: 1,
      price: '24.00',
      condition: 'NM',
    },
    {
      name: 'Wrath of God',
      set: 'DMC',
      cost: '{2}{W}{W}',
      colors: 'w',
      rarity: 'rare',
      qty: 2,
      price: '6.50',
      condition: 'NM',
    },
    {
      name: 'Krenko, Mob Boss',
      set: 'OGW',
      cost: '{2}{R}{R}',
      colors: 'r',
      rarity: 'rare',
      qty: 1,
      price: '4.10',
      condition: 'NM',
    },
  ],

  // Deck builder — sections with cards
  builder: {
    deck: {
      name: 'The Ur-Dragon',
      commander: 'The Ur-Dragon',
      format: 'Commander',
      colors: 'wubrg',
      count: 100,
      coverage: 87,
    },
    sections: [
      {
        name: 'Commander',
        cards: [{ name: 'The Ur-Dragon', cost: '{4}{W}{U}{B}{R}{G}', qty: 1, owned: true }],
      },
      {
        name: 'Creatures',
        cards: [
          { name: 'Dragonlord Atarka', cost: '{6}{R}{G}', qty: 1, owned: true },
          { name: 'Scion of the Ur-Dragon', cost: '{3}{W}{U}{B}{R}{G}', qty: 1, owned: true },
          { name: 'Terror of the Peaks', cost: '{3}{R}{R}', qty: 1, owned: false },
          { name: 'Miirym, Sentinel Wyrm', cost: '{3}{G}{U}', qty: 1, owned: true },
        ],
      },
      {
        name: 'Ramp',
        cards: [
          { name: 'Sol Ring', cost: '{1}', qty: 1, owned: true },
          { name: 'Arcane Signet', cost: '{2}', qty: 1, owned: true },
          { name: 'Cultivate', cost: '{2}{G}', qty: 1, owned: false },
        ],
      },
      {
        name: 'Removal',
        cards: [
          { name: 'Swords to Plowshares', cost: '{W}', qty: 1, owned: true },
          { name: 'Cyclonic Rift', cost: '{6}{U}', qty: 1, owned: true },
        ],
      },
    ],
    curve: [
      { cmc: '0', count: 5, color: 'c' },
      { cmc: '1', count: 8, color: 'w' },
      { cmc: '2', count: 16, color: 'u' },
      { cmc: '3', count: 18, color: 'g' },
      { cmc: '4', count: 14, color: 'b' },
      { cmc: '5', count: 9, color: 'r' },
      { cmc: '6+', count: 12, color: 'multi' },
    ],
    distribution: [
      { color: 'w', count: 14 },
      { color: 'u', count: 18 },
      { color: 'b', count: 16 },
      { color: 'r', count: 15 },
      { color: 'g', count: 17 },
    ],
  },

  // Header global-search spotlight results
  searchGroups: [
    { group: 'Cards', items: ['Sol Ring', 'Sheoldred, the Apocalypse', 'Llanowar Elves'] },
    { group: 'Decks', items: ['The Ur-Dragon', 'Kinnan Ramp'] },
    { group: 'Collection', items: ['4 results in “rare” · blue'] },
  ],

  activity: [
    {
      icon: 'plus',
      text: 'Added 4\u00d7 Llanowar Elves',
      deck: 'The Ur-Dragon',
      time: '2h ago',
      tone: 'success',
    },
    {
      icon: 'edit',
      text: 'Renamed deck to Yawgmoth Reanimator',
      deck: '',
      time: '5h ago',
      tone: 'default',
    },
    {
      icon: 'box',
      text: 'Imported 38 cards from text',
      deck: 'Atraxa Superfriends',
      time: '1d ago',
      tone: 'default',
    },
    {
      icon: 'warn',
      text: 'Coverage dropped below 70%',
      deck: 'Krenko Goblins',
      time: '2d ago',
      tone: 'warning',
    },
  ],
};
